#!/bin/sh -x
PREFIX=$HOME/apps/openmpi133

if [ ! -f ./openmpi-1.3.3.tar.bz2 ]; then
	wget http://www.open-mpi.org/software/ompi/v1.3/downloads/openmpi-1.3.3.tar.bz2
fi
rm -rf openmpi-1.3.3
tar xjf openmpi-1.3.3.tar.bz2
cd openmpi-1.3.3
# Change the prefix as needed
./configure --prefix=$PREFIX
make
make install

export PATH=$PREFIX/bin:$PATH
export LD_LIBRARY_PATH=$PREFIX/lib:$PREFIX/lib/openmpi:$LD_LIBRARY_PATH
