#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -N life_tutorial
#PBS -l walltime=00:30:00
#PBS -j oe
#PBS -M anthony.d@asu.edu
#PBS -m bae

use gcc-mvapich-1.0.1

./mkinit 1024 1024 input_file

# cd $PBS_O_WORKDIR
cd $HOME/mpitutorial

make clean
make

mpiexec life --iterations 10 --rows 1024 --columns 1024 --initial input_file --output ending_file

